camunda.bpm.admin-user:
  id: demo
  password: demo
camunda.bpm:
  deployment-resource-pattern:
  - classpath*:**/*.bpmn
  - classpath*:**/*.bpmn20.xml
  - classpath*:**/*.dmn
  - classpath*:**/*.dmn11.xml
  - classpath*:**/*.form

spring.datasource.platform:
spring.datasource.driver-class-name: 
spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring.datasource.username: 
spring.datasource.password:
spring.jpa.hibernate.ddl-auto: